name: Duster Lint

on:
    push:
        branches: [ main ]
    pull_request:

jobs:
  duster:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - uses: php-actions/composer@v5
      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader

      - name: "copy .env.example to .env"
        run: cp .env.example .env

      - name: generate keys
        run: php artisan key:generate --force

      - name: "Duster Lint"
        uses: tighten/duster-action@v3
        with:
          args: lint
